name: "Shell Script Linter"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: azohra/shell-linter@v0.6.0
        with:
          path: "src/**/*.sh"
          severity: "error"
